package menzgenums;

public enum DaysOfTheWeek {
    DAYS_OF_THE_WEEK_MONDAY,
    DAYS_OF_THE_WEEK_TUESDAY,
    DAYS_OF_THE_WEEK_WEDNESDAY,
    DAYS_OF_THE_WEEK_THURSDAY,
    DAYS_OF_THE_WEEK_FRIDAY,
    DAYS_OF_THE_WEEK_SATURDAY,
    DAYS_OF_THE_WEEK_SUNDAY
}
